# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/PClean

language: julia
julia:
  - 1.5

# run these in parallel
env:
  - PCLEAN_EXAMPLE=flights
  - PCLEAN_EXAMPLE=hospital
  - PCLEAN_EXAMPLE=rents

script:
    julia -e 'using Pkg; Pkg.instantiate(); dir=ENV["PCLEAN_EXAMPLE"]; include("experiments/$dir/run.jl");'
